# Generated by Django 3.2.23 on 2023-11-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sedda'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedda',
            name='dasc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
